-- ============================================================
-- Seed script: EUTR Reference Types menu & permissions
-- Run against the Authorization database (API_AUTHZ)
-- ============================================================
-- Menu entry follows the same pattern as eutr-steps (id=1),
-- eutr-masters (id=21), eutr-templates (id=22), eutr-documents (id=23)
-- and eutr-sales-orders (id=24). The frontend expects:
--   code = "eutr-reference-types"
--   url  = "/eutr/reference-types"
--   parentId = <id of "EUTR system" parent menu>
--
-- Permission policies used by EutrReferenceTypesController:
--   EutrReferenceTypes.ReadAll   (POST get-all, GET list)
--   EutrReferenceTypes.ReadOne   (GET get-by-id/{id})
--   EutrReferenceTypes.Create    (POST)
--   EutrReferenceTypes.Update    (PUT {id})
--   EutrReferenceTypes.Delete    (DELETE {id}, POST delete-multi)
-- ============================================================

-- 1. Insert menu item (adjust parentId and sortOrder to match your environment)
-- INSERT INTO user_menu (Code, Name, Url, ParentId, SortOrder, Icon, HideInMenu, AppCode)
-- VALUES ('eutr-reference-types', 'EUTR reference types', '/eutr/reference-types', <EUTR_SYSTEM_PARENT_ID>, 5, NULL, 0, '<APP_CODE>');

-- 2. Insert permissions for the menu item
-- INSERT INTO menu_permission (MenuId, PermissionCode, PermissionName)
-- SELECT Id, 'ReadAll',  'Read All'  FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT Id, 'ReadOne',  'Read One'  FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT Id, 'Create',   'Create'    FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT Id, 'Update',   'Update'    FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT Id, 'Delete',   'Delete'    FROM user_menu WHERE Code = 'eutr-reference-types';

-- 3. Grant permissions to roles (repeat for each role that needs access)
-- INSERT INTO role_permission (RoleId, MenuId, PermissionCode)
-- SELECT <ROLE_ID>, Id, 'ReadAll'  FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT <ROLE_ID>, Id, 'ReadOne'  FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT <ROLE_ID>, Id, 'Create'   FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT <ROLE_ID>, Id, 'Update'   FROM user_menu WHERE Code = 'eutr-reference-types'
-- UNION ALL
-- SELECT <ROLE_ID>, Id, 'Delete'   FROM user_menu WHERE Code = 'eutr-reference-types';

-- NOTE: Table and column names are approximate — verify against the actual
-- authorization database schema before running. Replace placeholder values
-- (<EUTR_SYSTEM_PARENT_ID>, <APP_CODE>, <ROLE_ID>) with real values.
